### ISSUE TITLE
Author avatar picture does not show

### ISSUE THREAD

**Issue by magnivar** [malmostad/wp-apps#16]
Web page requests a picture of the author in lower case but the actual picture exists with starting capitalized character.

Requested picture
https://webapps06.malmo.se/avatars/johpag/medium_quadrat.jpg

Working picture
https://webapps06.malmo.se/avatars/Johpag/medium_quadrat.jpg

Example page:
https://webapps04.malmo.se/nyheter/2016/09/30/halla-dar-johanna-palm/

**Comment by martent** [comment]
This turned out to be what looks like a normalisation problem with username standards in different LDAP catalogs. WP gets the usernames in lowercase, the Dashboard had some usernames pre 2015-06 in mixed case.

I provided a workaround so both lowercase usernames for all avatars works, as well as those 51 mixed case usernames pre 2015-06.

This doesn't mean that the usernames in avatars URL's, which are served static files, are case insensitive, but both versions of the affected 51 usernames work now.

The standard continues to be lowercase.

You may need to make a hard reload for the above example page to show the correct avatar since it might be cached in the browser.
